### ISSUE TITLE
Visual studio does not recognize wasp as a language

### ISSUE THREAD

**Issue by Daniellop1** [wasp-lang/vscode-wasp#2]
Hello, I have installed the extension for visual studio code and it does not detect it as a language

**Comment by Martinsos** [comment]
Hmmm that sounds very weird! So you installed it, but when you open .wasp file, there is no coloring? How do you know it does not detect it as a language? What is your version of VSCode? OS?

**Comment by Daniellop1** [comment]
> Hmmm that sounds very weird! So you installed it, but when you open .wasp file, there is no coloring? How do you know it does not detect it as a language? What is your version of VSCode? OS?

That's exactly what happened

**Comment by Daniellop1** [comment]
I have fixed the problem, it is due to a bad extension configuration.
