### ISSUE TITLE
Fix syntax highlighting for comments

### ISSUE THREAD

**Issue by sodic** [wasp-lang/vscode-wasp#8]
Comments are sometimes not properly highlighted (it sometimes happens when `//` comes after some code, but not always, could be related to commas at the ends of lines):
![image](https://user-images.githubusercontent.com/22752307/211174733-2b89040b-e6f4-4eaa-8a0d-0b4cb0318263.png)

**Comment by Martinsos** [comment]
Specifically, when it is a comment starting with `//` that starts at the end of the line of the code.

**Comment by infomiho** [comment]
Couple of cases when it happens:



![Image](https://github.com/wasp-lang/vscode-wasp/assets/2223680/3cad500a-5fc5-42d1-96dd-de27291d354e)
![Image](https://github.com/wasp-lang/vscode-wasp/assets/2223680/37726bf9-0526-481f-ae78-ddf9f7c47393)
![Image](https://github.com/wasp-lang/vscode-wasp/assets/2223680/01282f67-7ec8-405d-8601-5f082196ecb2)
